name: test winget install komac

on:
  workflow_dispatch: 

jobs:
  test-winget-install-komac:
    runs-on: windows-latest
    steps:
    - name: Install komac using winget
      run: |
        winget install komac --accept-source-agreements --accept-package-agreements --location "C:\Program Files\Komac"
    - name: Verify komac installation
      run: |
        cd "C:\Program Files\Komac"
        komac --version
