name: test winget install komac

on:
  workflow_dispatch: 

jobs:
  test-winget-install-komac:
    runs-on: windows-latest
    steps:
    - name: Install komac using winget
      run: |
        winget install komac --accept-package-agreements
    - name: Verify komac installation
      run: |
        komac --version
