name: test winget install komac

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  test-winget-install-komac:
    runs-on: windows-latest
<<<<<<< HEAD
    steps:
    - name: Install komac using winget
      run: |
        winget install --id=Komac.Komac -e --source=winget
    - name: Verify komac installation
      run: |
        komac --version
=======
      steps:
	  - name: Checkout repository
	      uses: actions/checkout@v3
	    - name: Install komac using winget
		  run: |
		    winget install -e --id Komac.Komac
	    - name: Verify komac installation
		  run: |
		    komac --version
>>>>>>> 545227748254843e2e4e48983abd60583638c397
